# -*- coding: utf-8 -*-
"""churn_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AM7KyKYIgV4JIVmVdStMLMtE1MLYgpkP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv')

df.head()

df.info()

df.isnull().sum()

df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

df['TotalCharges'].fillna(
    df['TotalCharges'].median(),
    inplace=True
)

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.shape

sns.countplot(x='Churn', data=df)
plt.show()

churn_rate = (
    df['Churn'].value_counts()['Yes']
    / len(df)
) * 100

print(churn_rate)

sns.countplot(
    x='Contract',
    hue='Churn',
    data=df
)

plt.xticks(rotation=45)
plt.show()

sns.countplot(
    x='PaymentMethod',
    hue='Churn',
    data=df
)

plt.xticks(rotation=90)
plt.show()

sns.countplot(
    x='InternetService',
    hue='Churn',
    data=df
)

plt.show()

sns.boxplot(
    x='Churn',
    y='MonthlyCharges',
    data=df
)

plt.show()

sns.histplot(df['tenure'], bins=30)
plt.show()

df['CustomerSegment'] = np.where(
    (df['tenure'] < 12)
    &
    (df['MonthlyCharges'] > 70),

    'High Risk',

    'Normal'
)

df['TenureGroup'] = pd.cut(
    df['tenure'],

    bins=[0,12,24,48,60,72],

    labels=[
        '0-1 Year',
        '1-2 Years',
        '2-4 Years',
        '4-5 Years',
        '5-6 Years'
    ]
)

sns.countplot(
    x='TenureGroup',
    hue='Churn',
    data=df
)

plt.xticks(rotation=45)
plt.show()

df.to_csv(
    '../Dataset/cleaned_churn_data.csv',
    index=False
)

